#!/usr/bin/env bash
#comment
The OSI model is a conceptual model that characterizes the communication functions of a telecommunication system without regard to their underlying internal structure and technologyy
From the lowest to the highest level
