#!/usr/bin/env bash
#localhost and facebook ip changed
HOSTS_FILE="/etc/hosts"
cp "$HOSTS_FILE" "$HOSTS_FILE.bak"
sed -i "/localhost/d" "$HOSTS_FILE"
sed -i "/facebook\.com/d" "$HOSTS_FILE"
echo "127.0.0.2 localhost" >> "$HOSTS_FILE"
echo "8.8.8.8 facebook.com" >> "$HOSTS_FILE"
