#!/usr/bin/env bash
sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i '/^127\.0\.0\.1.*localhost$/s/^127\.0\.0\.1/127.0.0.2/' /etc/hosts
sudo sed -i '/facebook\.com$/d' /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
